### ISSUE TITLE
Add season column in anime lists

### ISSUE THREAD

**Issue by Melvinkooi** [Kazakuri/Shinjiru#29]
A similar program to this which has MAL and Hummingbird support called "Taiga" has a column where you can which anime was aired in which season. This is handy in certain situations as making a custom list for a certain season or to see which anime you've haven't watched or continue watching of that season. Anilist has a season line in the anime entries so i don't see why not add it.

An example in Taiga:
![example season column](https://cloud.githubusercontent.com/assets/11279045/6635620/5b10bfbc-c968-11e4-9c9e-9d03ba34e93e.png)

An example on Anilist:
![example season line](https://cloud.githubusercontent.com/assets/11279045/6635695/fe473a1c-c968-11e4-8386-57c65fefa957.png)

**Comment by Kazakuri** [comment]
The AniList API doesn't provide explicit season data for entries and calculating it using the start date isn't feasible since the start date is only included when loading the [full anime model](http://anilist-api.readthedocs.org/en/latest/anime.html) rather than the small anime models returned by loading the user list.
