### ISSUE TITLE
OS X: Missing icon, error message on increment

### ISSUE THREAD

**Issue by sotojuan** [Kazakuri/Shinjiru#33]
Trying out the OS X client and noticed two things:

First, while the window and tray icons work, the .app file has a [generic icon](http://i.imgur.com/kOtFLfI.png).

Second, when I incremented an episode count, I got [this error message](http://i.imgur.com/KRufw1o.png
). The increment worked and them message did not appear after incrementing again.

Aside from these the app works. Thanks for the hard work!

**Comment by Kazakuri** [comment]
Yeah, each platform has an independent way of setting the application icons and they all like to use their own format for them so I haven't gotten around to creating an .icns icon for Shinjiru yet and doing all the junk required for that. It'll come soon though.

As far as the QSharedPointer error goes, that turns up every once in a while but it doesn't seem to cause any harm. In the next update osx will start using a log file so that error won't pop up anymore. :smile:
