### ISSUE TITLE
Segfault when nyaa is down

### ISSUE THREAD

**Issue by richese** [Kazakuri/Shinjiru#50]
Got another bug  for you :smile: 

It happend today on 2.0 branch when nyaa was down. Master seems to works fine.

It always crashed after a few minutes (some timeout?).
The last log message was `Could not fetch torrents` from `src/gui/panels/torrentswidget.cpp:343` followed by crash.

**Comment by Kazakuri** [comment]
I can't immediately see why it would crash, since it called `TorrentRSS::error` and `TorrentsWidget::parseRSS` would have stopped running because it logged `Could not fetch torrents`

I tried to replicate it by redirecting nyaa.se to 127.0.0.2 via hosts and couldn't get it to crash, it'd always just display a blank table for me.

**Comment by Kazakuri** [comment]
Ahh, nevermind! If I redirect it to a non-routable address such as 10.255.255.1 I'm able to get it to crash.

When the request times out it ends up calling the finished slot anyways so just checking for an error there should fix it.
