### ISSUE TITLE
Application crashing since downloading latest version

### ISSUE THREAD

**Issue by Olymposlk** [Kazakuri/Shinjiru#55]
Hello there :) 

This is an awesome app and i love using it, i just downloaded the latest version (2.2.0) from the website and went to open it and now when it opens it gets to "user loaded" and then crashes out and closes. 

I have tried disconnecting my account and connecting again but that did not work i am not sure what else to try. 

I have the DMP file here if you want to review: 

https://www.dropbox.com/s/ybl0smaxhq5976r/6875616a-d85a-421b-a97b-98302925dc4c.dmp?dl=0

Thanks for making an awesome app though and keep up the hard work :) look forward to using it again.

Kind Regards

**Comment by Kazakuri** [comment]
Hey, I tried going through the crash dump (dmp) but it doesn't really show anything useful. It looks like it was an internal issue with the Qt library.

Do you have any more crash dumps you can upload to see if those have any more details?

Others things to try in the meantime would be trying to re-download it or seeing if the [previous version](http://shinjiru.me/download.php?v=2.1.0) works.
Additionally you can try renaming the Shinjiru folder in `%AppData%\Local\Kazakuri\Shinjiru` to something like ShinjiruBackup and seeing if launching it after helps.

**Comment by Olymposlk** [comment]
Hey 

Thank you for the fast response, please see the 6 dump files below 4 are from before renaming the %AppData%\Local\Kazakuri\Shinjiru folder and 2 are from after still no luck here. 

4 from before : 
https://www.dropbox.com/s/0mknllefss1g148/0abbda47-cb24-44bb-91d2-eb42688b2c07.dmp?dl=0
https://www.dropbox.com/s/8f19ye5vllfj0tj/9c7e2864-a1d5-4fc5-b4f1-a1265776d234.dmp?dl=0
https://www.dropbox.com/s/7dgtc54qlads67x/3085b33d-1cb0-4cd3-9e3c-a75c412026e8.dmp?dl=0
https://www.dropbox.com/s/tlvq2u7spy2frm9/abeb5fe3-1162-4279-b085-516924bc1c08.dmp?dl=0

2 after rename:
https://www.dropbox.com/s/wv58abx1cpet26m/a6391967-897f-43a1-945d-61f842e7a95d.dmp?dl=0
https://www.dropbox.com/s/xc94un29rkgdjnb/aa0c62ef-b127-4510-b608-8eba46ccc79c.dmp?dl=0

i then renamed the folder again and downloaded the old version as suggested and had the same issue please see below 4 dumps from these attempts: 

https://www.dropbox.com/s/z4o0g3ix6mcb35e/7d41be6e-52d4-4369-9829-a4eec0aa13c4.dmp?dl=0
https://www.dropbox.com/s/knnmgas15kjbyql/32a29d02-4a77-4294-b09c-96ffdbdc4986.dmp?dl=0
https://www.dropbox.com/s/z0a3sncpmrbdjri/a1d9986e-effb-4bd1-ada4-4ddeed5220e8.dmp?dl=0
https://www.dropbox.com/s/kwz2pv38vmeoz7h/f3c9313c-4e2a-457f-ad82-21b6e09fc215.dmp?dl=0

Hopefully some of these dumps give you some more information :) 

Let me know if you need anything more information from me, could it be something to do with my account settings on anilist? 

Thanks for the assistance. 

Kind Regards

**Comment by Kazakuri** [comment]
Oh, there we go. I see what's going on.
Yeah, I'm able to replicate the crash if I force Shinjiru to load your user.

Essentially what's going on is that AniList is returning the following data for you: [http://i.imgur.com/MhgAqsV.png](http://i.imgur.com/MhgAqsV.png)

Where it says `custom_list_anime` it shows that you have two custom lists, but where it says `custom_lists` it's providing data for three custom lists and the program crashes because it's trying to fetch the title for the third custom list.

On AniList itself this third custom list looks something like this: [http://i.imgur.com/WwN4pRJ.png](http://i.imgur.com/WwN4pRJ.png).

So what you can do is on your AniList profile you can add another custom list and give it a name to get rid of the crash. From there you could remove those anime from that custom list if they shouldn't be there or just leave them there if that's fine.

**Comment by Olymposlk** [comment]
Yep that sorted it! awesome thank you very much for your time and effort, not sure were the 3rd custom list came from. It was not there before the anilist update and i could not see it in my account settings ever :S odd but all sorted now. 

Thanks once again and have a good day, evening or night depending where you are :). 

Ill close this now as it has been resolved to :)
